id = "kotlin-dev"
name = "Kotlin DEV"
version = "0.4.2"
schema_version = 1
authors = ["evrsen", "cholwell", "illyrius666"]
description = "Kotlin language support."
repository = "https://github.com/XodiumSoftware/zed-kotlin-ext"

[language_servers.kotlin-dev-lsp]
name = "Kotlin LSP"
language = "Kotlin"

[grammars.kotlin]
repository = "https://github.com/fwcd/tree-sitter-kotlin"
commit = "1852ea17b7f60fb3f9d84e0b1555d56b46b39fb1"
